### ISSUE TITLE
Server Crash- Trying to blow up a spawner with tnt

### ISSUE THREAD

**Issue by ProsperCraft** [CAD97/SpawnerCraft2#11]
http://pastebin.com/4JWzZ0Vy

**Comment by CAD97** [comment]
I thought I had guarded against (and tested) this case... A fix will be up as soon as I get a chance (which may take a while because #SGDQ2015)

**Comment by CAD97** [comment]
Working on finishing up version 2.3 now. Should be pushed tomorrow, including this fix.
