### ISSUE TITLE
Crashes dedicate Forge 1.8 b1320 server while looking for client side classes

### ISSUE THREAD

**Issue by kreezxil** [CAD97/SpawnerCraft2#3]
SpawnerCraft2-1.8-2.0

crash report: http://pastebin.com/pkBtan44
fml server latest: http://pastebin.com/QkZfaLhA

client works great tho!

**Comment by CAD97** [comment]
I knew I forgot to check something... From a quick glance this looks like a simple case of me running code on the wrong side of the connection.

I won't say it's simple to fix, though, because as soon as I do that then it'll take forever to fix. I will, however, take a look at it right now.

**Comment by CAD97** [comment]
[Release 1.8-2.0a](https://github.com/CAD97/SpawnerCraft2/releases/tag/1.8-2.0a) fixes this issue. Thanks for reporting it!

Sometimes I just forget about the whole sided part of Minecraft.

**Comment by kreezxil** [comment]
Sweet I'll try it again later today.
